// ABOUTME: Integrates Basket collections and blocks with the Are.na API.
// ABOUTME: Handles authentication, channel syncing, media uploads, and metadata updates.
import { Buffer } from "buffer";
import * as FileSystem from "expo-file-system";
import {
  Block,
  Collection,
  DatabaseBlockInsert,
  LastSyncedInfo,
  RemoteSourceType,
} from "./dataTypes";
import { BlockType, MimeType } from "./mimeTypes";
import {
  buildArenaBlockRequest,
  buildArenaConnectionRequest,
  buildArenaPresignRequest,
  detectImageContentType,
  getArenaUploadFilename,
  getArenaUploadSourceUrl,
  mapArenaConnectionBatch,
} from "./arenaRequests";
import { logError } from "./errors";
import { withQueryParams } from "./url";
import {
  ArenaUpdatedBlocksKey,
  ArenaUpdatedChannelsKey,
  getItem,
  setItem,
} from "./mmkv";
import { getCreatedByForRemote } from "./remote";
import { mapSnakeCaseToCamelCaseProperties } from "./dbUtils";

export const ArenaClientId = process.env.EXPO_PUBLIC_ARENA_CLIENT_ID!;
export const ArenaClientSecret = process.env.EXPO_PUBLIC_ARENA_CLIENT_SECRET!;
export const ArenaGraphqlKey = process.env.EXPO_PUBLIC_ARENA_GRAPHQL_KEY!;
export const ArenaTokenStorageKey = "arena-token";
export const GatherArenaAttribution =
  "created with [Gather](https://gather.directory/)";

enum ArenaVisibility {
  Public = "public",
  Closed = "closed",
  Private = "private",
}

interface ArenaConnection {
  connected_at: string;
  user: {
    id: number;
    slug: string;
  };
}

export interface ArenaChannelInfo {
  id: number;
  title: string;
  created_at: string;
  updated_at: string;
  added_to_at: string;
  published: boolean;
  open: boolean;
  collaboration: boolean;
  collaborator_count: number;
  slug: string;
  length: number;
  kind: string;
  status: string;
  user_id: number;
  follower_count: number;
  metadata: Metadata;
  contents: RawArenaChannelItem[];
  owner: RawArenaUser;
}
// Generated by https://quicktype.io

export interface RawArenaUser {
  created_at: string;
  slug: string;
  first_name: string;
  last_name: string;
  full_name: string;
  avatar: string;
  avatar_image: AvatarImage;
  channel_count: number;
  following_count: number;
  profile_id: number;
  follower_count: number;
  initials: string;
  can_index: boolean;
  metadata: Metadata;
  is_premium: boolean;
  is_lifetime_premium: boolean;
  is_supporter: boolean;
  is_exceeding_connections_limit: boolean;
  is_confirmed: boolean;
  is_pending_reconfirmation: boolean;
  is_pending_confirmation: boolean;
  badge: string;
  id: number;
  base_class: string;
  class: string;
}

export interface AvatarImage {
  thumb: string;
  display: string;
}

export interface Metadata {
  description: null | string;
}

export type ArenaClass =
  | "Image"
  | "Text"
  | "Link"
  | "Media"
  | "Attachment"
  | "Embed"
  | "Block"
  | "PendingBlock";
export interface RawArenaChannelItem {
  id: string;
  title: string;
  content: string;
  content_html?: string;
  created_at: string;
  updated_at: string;
  description_html?: string;
  description: string;
  image?: {
    content_type: string;
    display: { url: string };
    square: { url: string };
    thumb: { url: string };
    original: {
      url: string;
    };
  } | null;
  source: {
    url: string;
  } | null;
  url: string;
  base_class: "Block" | "Channel";
  class: ArenaClass;
  connected_at: string;
  connected_by_user_id: string;
  connected_by_user_slug: string;
  embed?: {
    url: null;
    type: string;
    title: null;
    author_name: string;
    author_url: string;
    source_url: null;
    thumbnail_url: null;
    width: number;
    height: number;
    html: string;
  };
  attachment?: {
    file_name: string;
    file_size: number;
    file_size_display: string;
    content_type: string;
    extension: string;
    url: string;
  };
  user: RawArenaUser;
}

// Generated by https://quicktype.io
export interface RawArenaBlock {
  title: string;
  updated_at: string;
  created_at: string;
  connected_at: string | null;
  state: string;
  comment_count: number;
  generated_title: string;
  content_html: string;
  description_html: string;
  visibility: string;
  content: string;
  description: string;
  image: {
    content_type: string;
    display: { url: string };
    square: { url: string };
    thumb: { url: string };
    original: {
      url: string;
    };
  } | null;
  source: {
    url: string;
  } | null;
  embed: {
    url: null;
    type: string;
    title: null;
    author_name: string;
    author_url: string;
    source_url: null;
    thumbnail_url: null;
    width: number;
    height: number;
    html: string;
  } | null;
  attachment: {
    file_name: string;
    file_size: number;
    file_size_display: string;
    content_type: string;
    extension: string;
    url: string;
  };
  metadata: null;
  id: number;
  base_class: "Block" | "Channel";
  class: ArenaClass;
  user: RawArenaUser;
  connections: Connection[];
}

export interface Connection {
  id: number;
  title: string;
  created_at: string;
  updated_at: string;
  added_to_at: string;
  published: boolean;
  open: boolean;
  collaboration: boolean;
  slug: string;
  length: number;
  kind: string;
  status: string;
  user_id: number;
  metadata: Metadata;
  share_link: null;
  base_class: string;
}

export interface AvatarImage {
  thumb: string;
  display: string;
}

export function apiUrl(
  baseUrl: string,
  path: string,
  params?: Record<string, any>,
): string {
  const url = `${baseUrl}${path}`;
  return withQueryParams(url, params || {});
}

export function nextUrlFromResponse(
  baseUrl: string,
  path: string,
  params: Record<string, any>,
  response: any,
): string | undefined {
  // Handle v3 meta.has_more_pages pagination
  if (response.meta?.has_more_pages) {
    const currPage =
      response.meta.current_page || response.page || response.current_page || 1;
    return apiUrl(baseUrl, path, { ...params, page: currPage + 1 });
  }
  // Fallback to v2 pagination
  const { page, length, per, current_page } = response;
  let currPage = page || current_page;
  if (currPage && per && length && currPage * per < length) {
    return apiUrl(baseUrl, path, { ...params, page: currPage + 1 });
  }
}

export function nextUrlFromArenaContentsResponse(
  baseUrl: string,
  path: string,
  params: Record<string, any>,
  response: any,
  perPage: number = 20,
): string | undefined {
  // v3 uses meta.has_more_pages
  if (response.meta?.has_more_pages) {
    const currPage = response.meta.current_page || Number(params.page) || 1;
    return apiUrl(baseUrl, path, { ...params, page: currPage + 1 });
  }
  // v2 fallback: check if contents array is full page
  const items = getContentsFromResponse(response);
  if (items.length === perPage) {
    return apiUrl(baseUrl, path, {
      ...params,
      page: (Number(params.page) || 1) + 1,
    });
  }
}

const ArenaApiUrl = "https://api.are.na/v3";
const ArenaGraphqlApi = "https://api.are.na/graphql";
const ArenaChannelsApi = "https://api.are.na/v3/channels";
const ArenaSearchApi = "https://api.are.na/v3/search";
export const ArenaChannelRegex =
  /(?:https:\/\/)?(?:www\.)?are\.na\/[\w-]+\/([\w-]+)/;

/**
 * Extract a plain string from a v3 description/content field that may be
 * either a string (v2) or an object `{ plain, html, markdown }` (v3).
 */
function normalizeArenaText(val: any): string {
  if (val == null) return "";
  if (typeof val === "string") return val;
  if (typeof val === "object") return val.plain ?? val.markdown ?? "";
  return String(val);
}

/**
 * Normalize a v3 REST block/item into the RawArenaChannelItem shape
 * expected by the rest of the codebase (v2 field names).
 *
 * Key v3 differences handled:
 *  - `type` / `base_type` instead of `class` / `base_class`
 *  - `description` and `content` can be objects `{plain, html, markdown}`
 *  - `image.small.src` instead of `image.thumb.url`
 *  - `image.medium.src` instead of `image.display.url`
 *  - `image.src` instead of `image.original.url`
 *  - `connection.connected_at` / `connection.connected_by` instead of
 *    top-level `connected_at` / `connected_by_user_*`
 *  - `user` shape has `avatar` instead of `avatar_image`
 */
function normalizeV3Block(raw: any): RawArenaChannelItem {
  // If it already has `class`, it's already v2 (e.g. from GraphQL mapper)
  if (raw.class && raw.base_class) return raw as RawArenaChannelItem;

  const arenaClass: ArenaClass =
    raw.class ?? raw.type ?? raw.__typename ?? "Block";
  const baseClass = raw.base_class ?? raw.base_type ?? "Block";

  // Normalize image field from v3 shape to v2 shape
  let image = raw.image;
  if (image && !image.display) {
    image = {
      ...image,
      content_type: image.content_type ?? "image/jpeg",
      display: { url: image.medium?.src ?? image.src ?? image.large?.src ?? "" },
      square: { url: image.square?.src ?? image.small?.src ?? "" },
      thumb: { url: image.small?.src ?? image.square?.src ?? "" },
      original: { url: image.src ?? image.large?.src ?? "" },
    };
  }

  // Normalize connection info
  const connection = raw.connection;
  const connectedAt =
    raw.connected_at ?? connection?.connected_at ?? "";
  const connectedByUserId =
    raw.connected_by_user_id ??
    connection?.connected_by?.id?.toString() ??
    "";
  const connectedByUserSlug =
    raw.connected_by_user_slug ??
    connection?.connected_by?.slug ??
    "";

  // Normalize user avatar
  const user = raw.user ? {
    ...raw.user,
    avatar_image: raw.user.avatar_image ?? {
      thumb: raw.user.avatar ?? "",
      display: raw.user.avatar ?? "",
    },
  } : raw.user;

  return {
    ...raw,
    id: raw.id?.toString?.() ?? raw.id,
    class: arenaClass,
    base_class: baseClass,
    description: normalizeArenaText(raw.description),
    content: arenaClass === "Text"
      ? normalizeArenaText(raw.content)
      : raw.content,
    image: image ?? null,
    connected_at: connectedAt,
    connected_by_user_id: connectedByUserId,
    connected_by_user_slug: connectedByUserSlug,
    user,
  } as RawArenaChannelItem;
}

/**
 * Normalize a v3 channel response to ArenaChannelInfo shape.
 * Handles single-channel endpoints like /v3/channels/{slug}.
 */
function normalizeV3Channel(raw: any): ArenaChannelInfo {
  const description = normalizeArenaText(raw.description);
  return {
    ...raw,
    status: raw.status ?? raw.visibility ?? "closed",
    length: raw.length ?? raw.counts?.blocks ?? 0,
    metadata: { description, ...(raw.metadata ?? {}) },
    owner: raw.owner ? {
      ...raw.owner,
      avatar_image: raw.owner.avatar_image ?? {
        thumb: raw.owner.avatar ?? "",
        display: raw.owner.avatar ?? "",
      },
    } : raw.owner,
    added_to_at: raw.added_to_at ?? raw.updated_at,
    contents: raw.contents ?? [],
  } as ArenaChannelInfo;
}

/**
 * Extract the contents/data array from a v3 response that may use
 * either `contents` (v2) or `data` (v3).
 */
function getContentsFromResponse(respBody: any): any[] {
  return respBody.contents ?? respBody.data ?? [];
}

function maybeParseChannelIdentifierFromUrl(maybeChannelUrl: string): string {
  if (ArenaChannelRegex.test(maybeChannelUrl)) {
    return maybeChannelUrl.match(ArenaChannelRegex)![1];
  }

  return maybeChannelUrl;
}

export function transformChannelUrlToApiUrl(url: string): string {
  const maybeChannelUrl = url.trim();
  if (maybeChannelUrl.startsWith(ArenaChannelsApi)) {
    return maybeChannelUrl;
  }

  const channel = maybeParseChannelIdentifierFromUrl(maybeChannelUrl);
  return `${ArenaChannelsApi}/${channel}`;
}

function escapeArenaStrings(str?: string): string | undefined {
  if (!str) {
    return str;
  }
  return str.replaceAll("&amp;", "&");
}

export async function getChannelThumb(
  channelIdOrUrl: string,
  { accessToken }: { accessToken?: string | null } = {},
): Promise<RawArenaChannelItem[]> {
  const channelId = maybeParseChannelIdentifierFromUrl(channelIdOrUrl);
  // v3 has no /thumb endpoint; fetch first page of contents instead
  const url = `${ArenaChannelsApi}/${channelId}/contents?per=20`;
  const resp = await fetch(url, {
    headers: {
      ...(accessToken ? { Authorization: `Bearer ${accessToken}` } : {}),
    },
  });
  if (!resp.ok) {
    throw new Error(`${resp.status}: failed to fetch channel thumb`);
  }
  const respBody = await resp.json();
  const items = getContentsFromResponse(respBody)
    .map(normalizeV3Block)
    .filter((c) => c.base_class === "Block" && c.class !== "Block");
  return items;
}

function mapListChannelItemsResponseToItems(
  result: ListChannelBlocksResult,
): RawArenaChannelItem[] {
  return result.data.channel.blokks.map<RawArenaChannelItem>((block) => {
    const { user, connection_to, __typename, url, id, ...rest } = block;
    let blockInfo = {};
    switch (__typename) {
      case "Link":
        blockInfo = {
          content: block.image_url,
        };
        break;
      case "Image":
        blockInfo = {
          image: {
            content_type: block.content_type,
            display: { url: block.display },
          },
        };
        break;
      case "Embed":
        blockInfo = {
          embed: {
            url: block.embed_url,
          },
        };
        break;
      case "Attachment":
        blockInfo = {
          attachment: {
            content_type: block.content_type,
            url: block.file_url,
          },
        };
        break;
    }
    return {
      ...rest,
      id: id.toString(),
      connected_at: connection_to.connected_at,
      connected_by_user_id: connection_to.user.id.toString(),
      connected_by_user_slug: connection_to.user.slug,
      class: __typename,
      base_class: "Block",
      // @ts-ignore
      user: user as RawArenaUser,
      url: `https://are.na/${url}`,
      ...blockInfo,
    } as RawArenaChannelItem;
  });
}

const DefaultBlockPer = 30;
export async function getChannelItemsPaginated(
  channelId: string,
  {
    accessToken,
    page = 1,
    per = DefaultBlockPer,
  }: { accessToken?: string | null; page?: number; per?: number } = {},
): Promise<RawArenaChannelItem[]> {
  const baseQuery = listChannelBlocksQuery({ channelId, per, page });
  console.log(
    `[Arena GraphQL] Fetching channel ${channelId} page=${page} per=${per}`,
  );
  const resp = await fetch(ArenaGraphqlApi, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${accessToken}`,
      "Content-Type": "application/json",
      "X-APP-TOKEN": ArenaGraphqlKey,
    },
    body: JSON.stringify({
      query: baseQuery,
    }),
  });
  const respBody = await resp.json();
  if (!resp.ok || respBody.errors) {
    console.error(
      `[Arena GraphQL] Error fetching channel ${channelId}:`,
      resp.status,
      JSON.stringify(respBody.errors ?? respBody),
    );
    if (respBody.errors) {
      throw new Error(
        `GraphQL error: ${respBody.errors.map((e: any) => e.message).join(", ")}`,
      );
    }
  }
  if (!respBody.data?.channel?.blokks) {
    console.error(
      `[Arena GraphQL] Unexpected response shape for channel ${channelId}:`,
      JSON.stringify(respBody).slice(0, 500),
    );
    return [];
  }
  console.log(
    `[Arena GraphQL] Got ${respBody.data.channel.blokks.length} blocks for channel ${channelId}`,
  );
  let contents: RawArenaChannelItem[] =
    mapListChannelItemsResponseToItems(respBody);
  return contents;
}

export async function getChannelItems(
  channelId: string,
  {
    accessToken,
    lastSyncedInfo,
  }: { accessToken?: string | null; lastSyncedInfo?: LastSyncedInfo | null },
) {
  console.log(
    "Fetching items for channel",
    channelId,
    ". Looking for items after ",
    lastSyncedInfo?.lastSyncedBlockCreatedAt,
  );
  let fetchedItems: RawArenaChannelItem[] = [];
  let newItemsFound = lastSyncedInfo ? false : true;
  const lastSyncedBlockCreatedAt = lastSyncedInfo?.lastSyncedBlockCreatedAt;
  let numItemsFetched = 0;
  let page = 1;
  const per = DefaultBlockPer;
  const baseQuery = listChannelBlocksQuery({ channelId, page });

  function nextQueryFromResponse(
    currentPage: number,
    per: number,
    items: RawArenaChannelItem[],
  ) {
    if (items.length === per) {
      return listChannelBlocksQuery({ channelId, page: currentPage + 1 });
    }
  }
  try {
    let nextQuery: string | undefined = baseQuery;
    while (nextQuery) {
      let contents = await getChannelItemsPaginated(channelId, {
        page,
        per,
        accessToken,
      });
      numItemsFetched += contents.length;
      const stopIdx = lastSyncedBlockCreatedAt
        ? contents.findIndex(
            (c) =>
              new Date(c.connected_at).getTime() <
              new Date(lastSyncedBlockCreatedAt).getTime(),
          )
        : null;
      console.log("stopidx", stopIdx, lastSyncedBlockCreatedAt);

      if (stopIdx && stopIdx > -1) {
        contents = contents.slice(0, stopIdx);
      }
      fetchedItems.push(...contents);

      if (stopIdx !== null && stopIdx > -1) {
        // we finished fetching all the items we needed
        break;
      }

      nextQuery = nextQueryFromResponse(page, per, contents);
      page++;
    }
  } catch (e) {
    logError(e);
    throw e;
  }
  console.log(
    `Fetched ${numItemsFetched} items. Returned ${fetchedItems.length} items.`,
  );
  return fetchedItems;
}

export async function getChannelInfo(
  channelId: string,
  accessToken?: string | null,
): Promise<Omit<ArenaChannelInfo, "contents">> {
  const baseUrl = `${ArenaChannelsApi}/${channelId}`;
  try {
    const resp = await fetch(baseUrl, {
      headers: {
        ...(accessToken ? { Authorization: `Bearer ${accessToken}` } : {}),
      },
    });
    const respBody = await resp.json();
    if (!resp.ok) {
      throw new Error(
        `${resp.status}: failed to fetch channel info for ${channelId} (url=${baseUrl}, authenticated=${!!accessToken}): ${resp.statusText}`,
      );
    }
    const { contents, data, ...rest } = respBody;
    return normalizeV3Channel(rest) as ArenaChannelInfo;
  } catch (e) {
    logError(e);
    throw e;
  }
}

export async function getChannelInfoFromUrl(
  url: string,
  accessToken?: string | null,
): Promise<ArenaChannelInfo> {
  const channelBaseUrl = transformChannelUrlToApiUrl(url);
  console.log("getting arena info from url", channelBaseUrl);
  const authHeaders = accessToken
    ? { Authorization: `Bearer ${accessToken}` }
    : {};

  // 1. Fetch channel metadata
  let channelInfo: any;
  try {
    const resp = await fetch(channelBaseUrl, { headers: authHeaders });
    const respBody = await resp.json();
    if (!resp.ok) {
      throw new Error(`${resp.status}: failed to fetch channel info`);
    }
    // v3 single-channel response has no `contents`; v2 may include them.
    const inlineContents = getContentsFromResponse(respBody);
    channelInfo = normalizeV3Channel(respBody);

    // If the response included contents inline (v2 style), use them directly
    if (inlineContents.length > 0) {
      channelInfo.contents = inlineContents.map(normalizeV3Block);
    }
  } catch (e) {
    logError(e);
    throw e;
  }

  // 2. Fetch contents from /contents endpoint (paginated)
  let fetchedItems: RawArenaChannelItem[] = [];
  try {
    const contentsBaseUrl = `${channelBaseUrl}/contents`;
    let nextUrl: string | undefined = contentsBaseUrl;
    while (nextUrl) {
      const resp = await fetch(nextUrl, { headers: authHeaders });
      const respBody = await resp.json();
      if (!resp.ok) {
        throw new Error(`${resp.status}: failed to fetch channel contents`);
      }
      let items: RawArenaChannelItem[] = getContentsFromResponse(respBody)
        .map(normalizeV3Block);
      items = items.filter(
        // NOTE: class = block only if are.na has failed to process it
        (c) => c.base_class === "Block" && c.class !== "Block",
      );
      items = items.map((c) => ({
        ...c,
        title: escapeArenaStrings(c.title),
        description: escapeArenaStrings(c.description),
        content: c.class === "Text" ? escapeArenaStrings(c.content) : c.content,
      }));
      fetchedItems.push(...items);
      nextUrl = nextUrlFromResponse(contentsBaseUrl, "", {}, respBody);
    }
  } catch (e) {
    logError(e);
    throw e;
  }
  return { ...channelInfo, contents: fetchedItems } as ArenaChannelInfo;
}

export function arenaClassToBlockType(
  arenaItem: RawArenaChannelItem,
): BlockType {
  const { class: classVal, embed, attachment, image } = arenaItem;
  const typeVal = classVal ?? (arenaItem as any).type;
  switch (typeVal) {
    case "Image":
      return BlockType.Image;
    // TODO: figure this out
    /**
 * "attachment": {
"file_name": "bad793f1615be6750041f44435d6a734.pdf",
"file_size": 1828021,
"file_size_display": "1.74 MB",
"content_type": "application/pdf",
"extension": "pdf",
"url": "https://arena-attachments.s3.amazonaws.com/24342276/bad793f1615be6750041f44435d6a734.pdf?1698188778"
},
 */
    case "Attachment":
      return BlockType.Document;
    case "Text":
      return BlockType.Text;
    case "Link":
    case "Embed":
      return BlockType.Link;
    /**
 * "embed": {
"url": null,
"type": "video",
"title": null,
"author_name": "i luv ur fit",
"author_url": "https://www.tiktok.com/@iluvurfit",
"source_url": null,
"thumbnail_url": null,
"width": 340,
"height": 700,
"html": "<iframe class=\"embedly-embed\" src=\"https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.tiktok.com%2Fembed%2Fv2%2F7289096161972145454&wmode=transparent&display_name=tiktok&url=https%3A%2F%2Fwww.tiktok.com%2Ft%2FZT8hD1Bog%2F&image=https%3A%2F%2Fp16-sign.tiktokcdn-us.com%2Fobj%2Ftos-useast5-p-0068-tx%2Fb315ba9606dc43218406892eb4553159_1697124965%3Fx-expires%3D1697605200%26x-signature%3DtCNQfgJ4KixPZxFCJQAGxX39140%253D&key=95f38852bd9b4f51ba7e5c8900281d06&type=text%2Fhtml&schema=tiktok\" width=\"340\" height=\"700\" scrolling=\"no\" title=\"tiktok embed\" frameborder=\"0\" allow=\"autoplay; fullscreen; encrypted-media; picture-in-picture;\" allowfullscreen=\"true\"></iframe>"
},
 */
    // TODO: actually handle this and use embed, need to figure out what embed url to use since URL is empty, for now it just
    // shows an image.
    // this should honestly probably be Video Rather than anything with an embed.
    case "Media":
      return embed?.url ? BlockType.Link : BlockType.Image;
    default:
      throw new Error(
        `Unhandled arena class: ${typeVal}, ${JSON.stringify(arenaItem)}`,
      );
  }
}

export function arenaClassToMimeType({
  class: classVal,
  embed,
  attachment,
  image,
  ...rest
}: RawArenaChannelItem): MimeType | undefined {
  const typeVal = classVal ?? (rest as any).type;
  switch (typeVal) {
    case "Image":
      return (image?.content_type as MimeType) ?? undefined;
    case "Attachment":
      return (attachment?.content_type as MimeType) ?? undefined;
    case "Text":
    case "Link":
      return undefined;
    case "Media":
    case "Embed":
      return embed?.url ? undefined : ((image?.content_type as MimeType) ?? undefined);
  }
}

interface ArenaPresignedFile {
  upload_url: string;
  key: string;
  content_type: string;
}

interface ArenaPresignResponse {
  files: ArenaPresignedFile[];
  expires_in: number;
}

async function getImageContentType(
  block: Block,
): Promise<string | undefined> {
  const encodedHeader = await FileSystem.readAsStringAsync(block.content, {
    encoding: FileSystem.EncodingType.Base64,
    position: 0,
    length: 12,
  });
  return detectImageContentType(
    Uint8Array.from(Buffer.from(encodedHeader, "base64")),
  );
}

async function getUploadContentType(block: Block): Promise<string> {
  if (block.type === BlockType.Image) {
    const detectedContentType = await getImageContentType(block);
    if (detectedContentType) {
      return detectedContentType;
    }
  }
  if (block.contentType) {
    return block.contentType;
  }
  throw new Error(`Missing content type for Are.na upload ${block.id}`);
}

async function uploadFile({
  block,
  accessToken,
}: {
  block: Block;
  accessToken: string;
}): Promise<string> {
  const contentType = await getUploadContentType(block);
  const filename = getArenaUploadFilename(block.id, contentType);
  const presignResponse = await fetch(`${ArenaApiUrl}/uploads/presign`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${accessToken}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify(buildArenaPresignRequest(filename, contentType)),
  });
  const presignBody = (await presignResponse.json()) as ArenaPresignResponse;
  if (!presignResponse.ok) {
    throw new Error(
      `Failed to presign Are.na upload ${presignResponse.status}: ${JSON.stringify(
        presignBody,
      )}`,
    );
  }

  const presignedFile = presignBody.files?.[0];
  if (
    !presignedFile?.upload_url ||
    !presignedFile.key ||
    !presignedFile.content_type
  ) {
    throw new Error(
      `Invalid Are.na presign response: ${JSON.stringify(presignBody)}`,
    );
  }

  const uploadResponse = await FileSystem.uploadAsync(
    presignedFile.upload_url,
    block.content,
    {
      httpMethod: "PUT",
      uploadType: FileSystem.FileSystemUploadType.BINARY_CONTENT,
      headers: {
        "Content-Type": presignedFile.content_type,
      },
    },
  );
  if (uploadResponse.status < 200 || uploadResponse.status >= 300) {
    throw new Error(
      `Failed to upload file to Are.na ${uploadResponse.status}: ${uploadResponse.body}`,
    );
  }
  return getArenaUploadSourceUrl(presignedFile.key);
}

async function getValueForBlock(
  block: Block,
  accessToken: string,
): Promise<any> {
  const { type, content, source } = block;
  switch (type) {
    case BlockType.Text:
      return content;
    case BlockType.Image:
    case BlockType.Video:
      if (content.startsWith("https://") || content.startsWith("http://")) {
        return content;
      }
      const url = await uploadFile({ block, accessToken });
      console.log("Uploaded file to arena", url);

      return url;
    case BlockType.Link:
      return source!;
    case BlockType.Audio:
    case BlockType.Document:
      throw new Error("unsupported type");
  }
}

export interface ListChannelBlocksResult {
  data: {
    channel: {
      blokks: ListChannelBlocksResultType[];
    };
  };
}

export interface ListChannelBlocksResultType {
  __typename: ArenaClass;
  id: number;
  created_at: string;
  updated_at: string;
  title: string;
  description: null | string;
  source: { url: string };
  url: string;
  user: {
    slug: string;
    name: string;
    avatar: string;
    id: number;
  };
  connection_to: {
    connected_at: string;
    user: {
      id: number;
      slug: string;
    };
  };
  image_url?: string;
  display?: string;
  embed_url?: string;
  file_url?: string;
  content_type?: string;
  content?: string;
}

const listChannelBlocksQuery = ({
  channelId,
  per = 30,
  page,
}: {
  channelId: string;
  per?: number;
  page: number;
}) => `
{
  channel(
    id:${channelId}
    ) {
      blokks(
      sort_by:CREATED_AT
      direction:DESC
      per: ${per}
      page: ${page}
      type: BLOCK
    ) {
        __typename
        ... on Model {
          id
          created_at(format: "%Y-%m-%dT%H:%M:%S.%LZ")
          updated_at(format: "%Y-%m-%dT%H:%M:%S.%LZ")
        }
        ... on ConnectableInterface {
          title
          description
          source {
            url
          }
          url: href
          user {
            slug
            name
            avatar
            id
          }
          connection_to(channel_id: ${channelId}) {
            connected_at: created_at(format: "%Y-%m-%dT%H:%M:%S.%LZ")
            user {
              id
              slug
            }
          }
        }
        ... on Link {
          image_url
        }
        ... on Text {
          content(format: PLAIN)
        }
        ... on Image {
          display: image_url(size: DISPLAY)
          content_type: file_content_type
        }
        ... on Embed {
          embed_url: image_url
        }
        ... on Attachment {
          file_url
          content_type: file_content_type
        }
      }
  }
}`;

export async function createBlock({
  block,
  channelIds,
  arenaToken,
}: {
  block: Block;
  channelIds: string[];
  arenaToken: string;
}): Promise<{
  arenaBlock: RawArenaBlock;
  connections: { [channelId: string]: ArenaConnection };
}> {
  let blockId = block.remoteSourceInfo?.arenaId;
  const connections: { [channelId: string]: ArenaConnection } = {};
  if (block.remoteSourceInfo?.arenaId) {
    console.log(
      `adding existing arena block ${block.remoteSourceInfo.arenaId} to channel`,
      channelIds,
    );
    const resp = await fetch(`${ArenaApiUrl}/connections`, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${arenaToken}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify(
        buildArenaConnectionRequest({
          arenaBlockId: block.remoteSourceInfo.arenaId,
          channelIds,
        }),
      ),
    });
    const response = await resp.json();
    if (!resp.ok) {
      logError(
        `failed to create connection for existing arena block ${
          resp.status
        }: ${JSON.stringify(response)}`,
      );
      throw new Error(JSON.stringify(response));
    }
    Object.assign(
      connections,
      mapArenaConnectionBatch({
        channelIds,
        connections: response.data ?? [],
      }),
    );
  } else {
    const value = await getValueForBlock(block, arenaToken);
    console.log("adding block to channel", channelIds, value);
    const { title, description: blockDescription } = block;
    let description = blockDescription || GatherArenaAttribution;
    // TODO: allow customization of the default description
    if (block.captureTime) {
      description += `\n\nCaptured: ${new Date(
        block.captureTime,
      ).toLocaleDateString()} ${new Date(
        block.captureTime,
      ).toLocaleTimeString()}`;
    }
    const resp = await fetch(`${ArenaApiUrl}/blocks`, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${arenaToken}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify(
        buildArenaBlockRequest({
          value,
          channelIds,
          title,
          description,
        }),
      ),
    });
    const response = await resp.json();
    if (!resp.ok) {
      logError(
        `failed to create block in arena ${resp.status}: ${JSON.stringify(
          response,
        )}`,
      );
      throw new Error(JSON.stringify(response));
    }
    Object.assign(
      connections,
      mapArenaConnectionBatch({
        channelIds,
        connections: channelIds.map(() => ({
          connected_at: response.created_at,
          connected_by: response.user,
        })),
      }),
    );
    blockId = response.id?.toString();
  }

  if (!blockId) {
    logError("failed to get block id from response");
    throw new Error("failed to get block id from response");
  }

  // getBlock is a best-effort enrichment call (mainly for the image field).
  // If it fails, we still have the essential block ID from the create response.
  // The local DB must save that ID so a later sync does not create a duplicate.
  let blockInfo: RawArenaBlock;
  try {
    blockInfo = normalizeV3Block(
      await getBlock(blockId, arenaToken),
    ) as unknown as RawArenaBlock;
  } catch (err) {
    logError(
      `[Arena] getBlock enrichment failed for ${blockId}, using minimal data: ${err}`
    );
    blockInfo = { id: Number(blockId) } as RawArenaBlock;
  }
  return {
    arenaBlock: blockInfo,
    connections,
  };
}

export async function updateArenaBlock({
  blockId,
  arenaToken,
  title,
  description,
}: {
  blockId: string;
  arenaToken: string;
  title?: string;
  description?: string;
}) {
  const body: Record<string, string> = {};
  if (title !== undefined) body.title = title || "";
  if (description !== undefined) body.description = description || "";
  const url = `${ArenaApiUrl}/blocks/${blockId}`;
  const updateMetadata = await fetch(url, {
    method: "PUT",
    headers: {
      Authorization: `Bearer ${arenaToken}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify(body),
  });
  if (!updateMetadata.ok) {
    logError(
      `failed to update block metadata in arena ${updateMetadata.status}`,
    );
    throw new Error(`${updateMetadata.status}: ${updateMetadata.statusText}`);
  }
  return updateMetadata;
}

export async function removeBlockFromChannel({
  blockId,
  channelId,
  arenaToken,
}: {
  blockId: string;
  channelId: string;
  arenaToken: string;
}): Promise<void> {
  const url = `${ArenaChannelsApi}/${channelId}/blocks/${blockId}`;
  console.log("deleting block from channel", channelId, blockId);
  const resp = await fetch(url, {
    method: "DELETE",
    headers: {
      Authorization: `Bearer ${arenaToken}`,
      "Content-Type": "application/json",
    },
  });
  const response = await resp.text();
  if (!resp.ok) {
    logError(
      `failed to remove block from arena channel ${
        resp.status
      }: ${JSON.stringify(response)}`,
    );
    // TODO: this handles case if block is already deleted, change after migration
    if (resp.status === 401) {
      return;
    }
    throw new Error(JSON.stringify(response));
  }
}

export async function getMyArenaUserInfo(
  accessToken: string,
): Promise<RawArenaUser> {
  const resp = await fetch(`${ArenaApiUrl}/me`, {
    headers: {
      Authorization: `Bearer ${accessToken}`,
    },
  });
  if (!resp.ok) {
    const text = await resp.text().catch(() => "");
    logError(`getMyArenaUserInfo failed: ${resp.status} ${text}`);
    throw new Error(`${resp.status}: failed to get user info from are.na`);
  }
  return resp.json();
}

export async function getArenaUserInfo(
  slug: string,
): Promise<RawArenaUser | null> {
  const resp = await fetch(`${ArenaApiUrl}/users/${slug}`, {});
  if (!resp.ok) {
    logError(`getArenaUserInfo failed: ${resp.status}`);
    return null;
  }
  return resp.json();
}

interface UserChannelResponse {
  channels: ArenaChannelInfo[];
  nextPage?: number;
}

function parseChannelListResponse(
  respBody: any,
  currentPage: number,
): UserChannelResponse {
  const rawItems = respBody.data || respBody.channels || [];
  const channels = rawItems
    .filter((item: any) => item != null && item.id != null)
    .map(normalizeV3Channel);
  // v3 uses meta.has_more_pages, v2 uses current_page/total_pages
  const hasMorePages =
    respBody.meta?.has_more_pages ??
    (respBody.current_page != null &&
      respBody.total_pages != null &&
      respBody.current_page < respBody.total_pages);
  return {
    channels,
    nextPage: hasMorePages ? currentPage + 1 : undefined,
  };
}

export async function getUserChannels(
  accessToken: string,
  {
    page = 1,
    per = 30,
    search,
  }: { page?: number; per?: number; search?: string } = {},
): Promise<UserChannelResponse> {
  const params: Record<string, any> = {
    type: "Channel",
    scope: "my",
    per,
    page,
  };
  if (search) {
    params.query = search;
  }
  const baseUrl = withQueryParams(`${ArenaSearchApi}`, params);
  try {
    const resp = await fetch(baseUrl, {
      headers: {
        Authorization: `Bearer ${accessToken}`,
      },
    });
    if (!resp.ok) {
      const text = await resp.text().catch(() => "");
      throw new Error(`${resp.status}: failed to fetch user channels: ${text}`);
    }
    const respBody = await resp.json();
    return parseChannelListResponse(respBody, page);
  } catch (e) {
    logError(e);
    throw e;
  }
}
export async function searchChannels(
  accessToken: string,
  {
    page = 1,
    per = 30,
    search,
  }: { page?: number; per?: number; search?: string } = {},
): Promise<UserChannelResponse> {
  const baseUrl = withQueryParams(`${ArenaSearchApi}`, {
    type: "Channel",
    query: search,
    page,
    per,
  });
  try {
    const resp = await fetch(baseUrl, {
      headers: {
        Authorization: `Bearer ${accessToken}`,
      },
    });
    if (!resp.ok) {
      const text = await resp.text().catch(() => "");
      throw new Error(`${resp.status}: failed to search channels: ${text}`);
    }
    const respBody = await resp.json();
    return parseChannelListResponse(respBody, page);
  } catch (e) {
    logError(e);
    throw e;
  }
}

export async function createChannel({
  accessToken,
  title,
  // TODO: make this a default setting in settings
  visibility = ArenaVisibility.Private,
}: {
  accessToken: string;
  title: string;
  visibility?: ArenaVisibility;
}): Promise<{
  newChannel: ArenaChannelInfo;
}> {
  const url = `${ArenaApiUrl}/channels`;
  const resp = await fetch(url, {
    method: "POST",
    body: JSON.stringify({
      title,
      description: GatherArenaAttribution,
      // v3 uses "visibility", v2 used "status"
      status: visibility,
      visibility,
    }),
    headers: {
      Authorization: `Bearer ${accessToken}`,
      "Content-Type": "application/json",
    },
  });
  const rawChannel = await resp.json();
  if (!resp.ok) {
    logError(`failed to create channel ${resp.status}: ${rawChannel}`);
    throw new Error(JSON.stringify(rawChannel));
  }
  const maybeChannel = normalizeV3Channel(rawChannel);
  await updateArenaChannel({
    channelId: maybeChannel.id.toString(),
    arenaToken: accessToken,
    description: GatherArenaAttribution,
  });

  return {
    newChannel: maybeChannel,
  };
}

export async function getBlock(
  blockId: string,
  arenaAccessToken?: string | null,
): Promise<RawArenaBlock> {
  const resp = await fetch(`${ArenaApiUrl}/blocks/${blockId}`, {
    headers: {
      ...(arenaAccessToken ? { Authorization: `Bearer ${arenaAccessToken}` } : {}),
      "Content-Type": "application/json",
    },
  });
  const json = await resp.json();
  if (!resp.ok) {
    logError(`${resp.status} failed to get block ${resp.statusText}`);
    throw new Error(`${resp.status} failed to get block ${resp.statusText}`);
  }
  return json;
}

type BlockFieldUpdate = {
  [k in keyof Block]: number;
};
interface UpdatedBlocks {
  [blockId: string]: BlockFieldUpdate;
}

export function getPendingBlockUpdates(): UpdatedBlocks {
  const updatedBlocks = getItem<UpdatedBlocks>(ArenaUpdatedBlocksKey);
  return updatedBlocks || {};
}

export function recordPendingBlockUpdate(
  blockId: string,
  updatedFields: (keyof Block)[],
) {
  const now = Date.now();
  const updatedBlocks = getPendingBlockUpdates();
  const existing = updatedBlocks[blockId] || {};
  setItem(ArenaUpdatedBlocksKey, {
    ...updatedBlocks,
    [blockId]: {
      ...existing,
      ...Object.fromEntries(updatedFields.map((key) => [key, now])),
    },
  });
}

export function removePendingBlockUpdate(blockId: string) {
  const updatedBlocks = getPendingBlockUpdates();
  delete updatedBlocks[blockId];
  setItem(ArenaUpdatedBlocksKey, updatedBlocks);
}

export function rawArenaBlocksToBlockInsertInfo(
  arenaBlocks: RawArenaChannelItem[],
): DatabaseBlockInsert[] {
  // Filter out PendingBlock items — these are blocks Arena is still
  // processing (e.g. image uploads). They'll be picked up on the next
  // sync cycle once Arena finishes processing them.
  return arenaBlocks
    .filter((block) => {
      const blockClass = block.class ?? (block as any).type;
      if (blockClass === "PendingBlock") {
        console.log(
          `[Arena Sync] Skipping PendingBlock arena_id=${block.id} title="${block.title}"`,
        );
        return false;
      }
      if (block.base_class === "Channel" || blockClass === "Channel") {
        console.log(
          `[Arena Sync] Skipping Channel arena_id=${block.id} title="${block.title}"`,
        );
        return false;
      }
      return true;
    })
    .map(rawArenaBlockToBlockInsertInfo);
}

export function rawArenaBlockToBlockInsertInfo(
  block: RawArenaChannelItem,
): DatabaseBlockInsert {
  const imageUrl = block.image?.display?.url ?? block.image?.original?.url;
  const contentValue =
    block.attachment?.url ||
    block.embed?.url ||
    imageUrl ||
    block.content;
  if (!contentValue) {
    console.error("MISSING CONTENT FOR ", block);
    logError(`MISSING CONTENT FOR ${block}`);
  }
  return {
    title: block.title,
    description: normalizeArenaText(block.description),
    content: contentValue,
    type: arenaClassToBlockType(block),
    contentType: arenaClassToMimeType(block),
    source: block.source?.url,
    createdBy: getCreatedByForRemote(RemoteSourceType.Arena, block.user.slug),
    remoteSourceType: RemoteSourceType.Arena,
    remoteSourceInfo: {
      arenaId: block.id,
      arenaClass: "Block",
    },
    remoteConnectedAt: block.connected_at,
    connectedBy: getCreatedByForRemote(
      RemoteSourceType.Arena,
      block.connected_by_user_slug,
    ),
  };
}
export function rawArenaBlockToBlock(block: RawArenaChannelItem): Block {
  return {
    id: block.id.toString(),
    ...rawArenaBlockToBlockInsertInfo(block),
    createdAt: new Date(block.created_at),
    updatedAt: new Date(block.updated_at),
    remoteConnectedAt: block.connected_at ? new Date(block.connected_at) : null,
    numConnections: 1,
    collectionIds: [],
  };
}
export function rawArenaChannelToCollection(
  channel: ArenaChannelInfo,
): Collection {
  return {
    ...mapSnakeCaseToCamelCaseProperties(channel),
    description: channel.metadata?.description || undefined,
    remoteSourceType: RemoteSourceType.Arena,
    numBlocks: channel.length,
    createdAt: new Date(channel.created_at),
    updatedAt: new Date(channel.updated_at),
    lastConnectedAt: new Date(channel.added_to_at),
    createdBy: getCreatedByForRemote(
      RemoteSourceType.Arena,
      channel.owner.slug,
    ),
    title: channel.title,
  };
}

type CollectionFieldUpdate = {
  [k in keyof Collection]: number;
};
interface UpdatedCollections {
  [collectionId: string]: CollectionFieldUpdate;
}

export function getPendingCollectionUpdates(): UpdatedCollections {
  const updatedCollections = getItem<UpdatedCollections>(
    ArenaUpdatedChannelsKey,
  );
  return updatedCollections || {};
}

export function recordPendingCollectionUpdate(
  collectionId: string,
  updatedFields: (keyof Collection)[],
) {
  const now = Date.now();
  const updatedCollections = getPendingCollectionUpdates();
  const existing = updatedCollections[collectionId] || {};
  setItem(ArenaUpdatedChannelsKey, {
    ...updatedCollections,
    [collectionId]: {
      ...existing,
      ...Object.fromEntries(updatedFields.map((key) => [key, now])),
    },
  });
}

export function removePendingCollectionUpdate(collectionId: string) {
  const updatedCollections = getPendingCollectionUpdates();
  delete updatedCollections[collectionId];
  setItem(ArenaUpdatedChannelsKey, updatedCollections);
}

export async function updateArenaChannel({
  channelId,
  arenaToken,
  title,
  description,
  status,
}: {
  channelId: string;
  arenaToken: string;
  title?: string;
  description?: string;
  status?: ArenaVisibility;
}) {
  console.log("updating channel", channelId, title, description, status);
  const updateMetadata = await fetch(ArenaGraphqlApi, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${arenaToken}`,
      "Content-Type": "application/json",
      "X-APP-TOKEN": ArenaGraphqlKey,
    },
    body: JSON.stringify({
      query: updateChannelMutation,
      variables: {
        id: channelId,
        title,
        description,
        status,
      },
    }),
  });
  if (!updateMetadata.ok) {
    logError(
      `failed to update block metadata in arena ${
        updateMetadata.status
      }: ${JSON.stringify(updateMetadata)}`,
    );
  }
  return updateMetadata;
}

const updateChannelMutation = `
  mutation updateChannelMutation(
    $id: ID!
    $title: String
    $description: String
    $visibility: ChannelVisibility
    $content_flag: ContentFlag
    $owner: ChannelMemberInput
  ) {
    update_channel(
      input: {
        id: $id
        title: $title
        description: $description
        visibility: $visibility
        content_flag: $content_flag
        owner: $owner
      }
    ) {
      channel {
        ...ManageChannel
      }
    }
  }
  fragment ManageChannel on Channel {
    id
    href
    title
    description(format: MARKDOWN)
    visibility
    content_flag
    can {
      destroy
      export
    }
    user {
      id
    }
    owner {
      __typename
      ... on User {
        id
      }
      ... on Group {
        id
      }
    }
    ...TransferChannel
  }
  fragment TransferChannel on Channel {
    id
    can {
      transfer
    }
    is_pending_transfer
    transfer_request {
      recipient {
        __typename
        ... on User {
          id
          name
        }
        ... on Group {
          id
          name
        }
      }
      is_recipient_member
    }
    visibility
  }
`;
